# pandas exploration
In this assignment you will select a data set and do some munging and analysis of it using `pandas`, Jupyter Notebooks, and associated Python-centric data science tools.

## Set up environment

The following lines ensure that `numpy` and `pandas` are installed in the notebook environment.  Depending on your system, this may not be necessary and may be removed.

In [258]:
!pip install numpy
!pip install pandas

Requirement already satisfied: numpy in /opt/anaconda3/lib/python3.11/site-packages (1.26.4)
Requirement already satisfied: pandas in /opt/anaconda3/lib/python3.11/site-packages (2.1.4)
Requirement already satisfied: numpy<2,>=1.23.2 in /opt/anaconda3/lib/python3.11/site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/shaw/.local/lib/python3.11/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/lib/python3.11/site-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /opt/anaconda3/lib/python3.11/site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in /Users/shaw/.local/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

Import the core data science libraries:

In [259]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

## Import the raw data
In this section, you will import the raw data into a `pandas` DataFrame.

In [260]:
df_2021 = pd.read_csv('data/data_2021.csv')
df_2021.head()

   ADMYR   CASEID  STFIPS  EDUC  MARSTAT  SERVICES  DETCRIM  NOPRIOR  PSOURCE  ARRESTS  EMPLOY  METHUSE  PSYPROB  PREG  GENDER  VET  LIVARAG  DAYWAIT  DSMCRIT  AGE  RACE  ETHNIC  DETNLF  PRIMINC  SUB1  SUB2  SUB3  ROUTE1  ROUTE2  ROUTE3  FREQ1  FREQ2  FREQ3  FRSTUSE1  FRSTUSE2  FRSTUSE3  HLTHINS  PRIMPAY  FREQ_ATND_SELF_HELP  ALCFLG  COKEFLG  MARFLG  HERFLG  METHFLG  OPSYNFLG  PCPFLG  HALLFLG  MTHAMFLG  AMPHFLG  STIMFLG  BENZFLG  TRNQFLG  BARBFLG  SEDHPFLG  INHFLG  OTCFLG  OTHERFLG  DIVISION  REGION  IDU  ALCDRUG  CBSA2020
0   2021  1284929       2     4        2         5       -9        1        1        0       4        2        1    -9       1    2        2        0        4    6     1       4       5        5     2     4    10       1       1       2      1      3      2         4         4         6        2        4                    1       1        0       1       0        0         0       0        0         1        0        0        0        0        0         0       0       0         0         9       4    0        3     11260
1   2021  1199988       2     2        1         5        3        0        7        0       4        2        1     2       2    2        2        0        7    2     5       4       5        4     4    10    19       2       2       2      3      2      3         1         3         1        4        4                    1       0        0       1       0        0         0       0        0         1        0        0        0        0        0         0       0       0         1         9       4    0        2        -9
2   2021  1179533       2     4        1         7       -9        0        1        0       3        2        2     2       2    2        3        0        4    6     1       4      -9        4     4     2     3       2       1       3      3      3      1         3         3         4        2        4                    1       1        1       1       0        0         0       0        0         0        0        0        0        0        0         0       0       0         0         9       4    0        3     21820
3   2021  1146520       2     2        2         7       -9        1        1        0       4        1        2     2       2    2        3        0        5    5     5       2       1        4     5     1     1       3      -9      -9      3     -9     -9         4        -9        -9        2        4                    1       0        0       0       1        0         0       0        0         0        0        0        0        0        0         0       0       0         0         9       4    0        2     11260
4   2021  1213798       2     2        1         7       -9        5        1        0       4        1        2     2       2    2        3        0        5    5     7       2       5        3     5     1     1       4      -9      -9      3     -9     -9         4        -9        -9        2        4                    1       0        0       0       1        0         0       0        0         0        0        0        0        0        0         0       0       0         0         9       4    1        2     11260

In [261]:
df_2019 = pd.read_csv('data/data_2019.csv')
df_2019.head()

   ADMYR   CASEID  STFIPS  CBSA2010  EDUC  MARSTAT  SERVICES  DETCRIM  NOPRIOR  PSOURCE  ARRESTS  EMPLOY  METHUSE  PSYPROB  PREG  GENDER  VET  LIVARAG  DAYWAIT  DSMCRIT  AGE  RACE  ETHNIC  DETNLF  PRIMINC  SUB1  SUB2  SUB3  ROUTE1  ROUTE2  ROUTE3  FREQ1  FREQ2  FREQ3  FRSTUSE1  FRSTUSE2  FRSTUSE3  HLTHINS  PRIMPAY  FREQ_ATND_SELF_HELP  ALCFLG  COKEFLG  MARFLG  HERFLG  METHFLG  OPSYNFLG  PCPFLG  HALLFLG  MTHAMFLG  AMPHFLG  STIMFLG  BENZFLG  TRNQFLG  BARBFLG  SEDHPFLG  INHFLG  OTCFLG  OTHERFLG  DIVISION  REGION  IDU  ALCDRUG
0   2019  1666221       2     27940     3        1         4       -9        0        3        0      -9        2        2     2       2    2        3        0        9    3     8       4      -9        4     2     4     1       1       2      -9     -9     -9     -9        -9        -9        -9        2        4                    1       1        0       1       0        0         0       0        0         0        0        0        0        0        0         0       0       0         0         9       4    0        3
1   2019  1570498       2        -9     3        1         7       -9        0        6        0       4        2        2     2       2    2        3        0        4    7     5       3       5        5     2     4     1       1       2      -9      1      1     -9         2         2        -9        4        1                    2       1        0       1       0        0         0       0        0         0        0        0        0        0        0         0       0       0         0         9       4    0        3
2   2019  1547352       2     27940     3        1         4       -9        3        2        0       4        2        1    -9       2    2        3        0        4    5     2       4       4        5     2     1     1       1      -9      -9      3     -9     -9         3        -9        -9        2        4                    1       1        0       0       0        0         0       0        0         0        0        0        0        0        0         0       0       0         0         9       4    0        1
3   2019  1510020       2        -9     3        1         7       -9        0        3        0       4        1        2     2       2    2        3        0        5    5     8       4       5        5     5     4    10       4       1       2      3      2      2         3         2         3        2        4                    1       0        0       1       1        0         0       0        0         1        0        0        0        0        0         0       0       0         0         9       4    1        2
4   2019  1585912       2        -9     3        4         7       -9        1        1        1       3        2        1     2       2    2        3        0       15    5     1       4      -9        4     2     4     1       1       5      -9      2      2     -9         3         3        -9        4        7                    1       1        0       1       0        0         0       0        0         0        0        0        0        0        0         0       0       0         0         9       4    0        3

## Data inspection
In this section, you will show enough of your data for a viewer to get a general sense of how the data is structured and any unique features of it.  Complete each of the indicated tasks in a Code cell, making sure to include a Markdown cell above each Code cell that explains what is being shown by the code.  
- Show 5 rows, selected at random, from the data set.
- Show each of the column names and their data types.
- Show any unique features of your chosen data set.

Feel free to add as many additional cells as you need to help explain the raw data.

In [262]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

- Display 5 randomly selected rows from the 2021 dataset

In [263]:
df_2021.sample(5)

         ADMYR   CASEID  STFIPS  EDUC  MARSTAT  SERVICES  DETCRIM  NOPRIOR  PSOURCE  ARRESTS  EMPLOY  METHUSE  PSYPROB  PREG  GENDER  VET  LIVARAG  DAYWAIT  DSMCRIT  AGE  RACE  ETHNIC  DETNLF  PRIMINC  SUB1  SUB2  SUB3  ROUTE1  ROUTE2  ROUTE3  FREQ1  FREQ2  FREQ3  FRSTUSE1  FRSTUSE2  FRSTUSE3  HLTHINS  PRIMPAY  FREQ_ATND_SELF_HELP  ALCFLG  COKEFLG  MARFLG  HERFLG  METHFLG  OPSYNFLG  PCPFLG  HALLFLG  MTHAMFLG  AMPHFLG  STIMFLG  BENZFLG  TRNQFLG  BARBFLG  SEDHPFLG  INHFLG  OTCFLG  OTHERFLG  DIVISION  REGION  IDU  ALCDRUG  CBSA2020
1346752   2021   963138      45     2        1         7        3        1        7        0      -9       -9        2    -9       1    2        2        0        1    2     4       4      -9        2     4     2    -9       2       1      -9      2      2     -9         2         3        -9        2        4                   -9       1        0       1       0        0         0       0        0         0        0        0        0        0        0         0       0       0         0         5       3    0        3     23500
388309    2021   319862       9     4        2         2       -9        2        3        0       4        2        2     2       2    2        3        0        8    7     5       4       5        4    13     4     1       1       2      -9      3      3     -9         7         2        -9        2       -9                    2       0        0       1       0        0         0       0        0         0        0        0        1        0        0         0       0       0         0         1       1    0        2     14860
125658    2021  1475068       4    -9        1         7       -9        5        1        0       4        2        2    -9       1    2       -9       -9        4    7    -9      -9       5        1     1     1     1      -9      -9      -9     -9     -9     -9        -9        -9        -9        2        4                    1       0        0       0       0        0         0       0        0         0        0        0        0        0        0         0       0       0         0         8       4   -9        0        -9
1224143   2021   388585      36     2        2         7       -9        0        1        0       4        1        1     2       2    2        3       -9        5   11     5       4       5        4     7     1     1       1      -9      -9      2     -9     -9         3        -9        -9       -9       -9                    1       0        0       0       0        0         1       0        0         0        0        0        0        0        0         0       0       0         0         2       1    0        2     13780
975136    2021   902548      37     4        4         7       -9        1        7        0       2        2        2    -9       1    2        1       -9       11    7     5       4      -9       -9    10     1     1       4      -9      -9      1     -9     -9         3        -9        -9       -9       -9                    4       0        0       0       0        0         0       0        0         1        0        0        0        0        0         0       0       0         0         5       3    1        2     48900

- Display 5 randomly selected rows from the 2019 dataset

In [264]:
df_2019.sample(5)

         ADMYR   CASEID  STFIPS  CBSA2010  EDUC  MARSTAT  SERVICES  DETCRIM  NOPRIOR  PSOURCE  ARRESTS  EMPLOY  METHUSE  PSYPROB  PREG  GENDER  VET  LIVARAG  DAYWAIT  DSMCRIT  AGE  RACE  ETHNIC  DETNLF  PRIMINC  SUB1  SUB2  SUB3  ROUTE1  ROUTE2  ROUTE3  FREQ1  FREQ2  FREQ3  FRSTUSE1  FRSTUSE2  FRSTUSE3  HLTHINS  PRIMPAY  FREQ_ATND_SELF_HELP  ALCFLG  COKEFLG  MARFLG  HERFLG  METHFLG  OPSYNFLG  PCPFLG  HALLFLG  MTHAMFLG  AMPHFLG  STIMFLG  BENZFLG  TRNQFLG  BARBFLG  SEDHPFLG  INHFLG  OTCFLG  OTHERFLG  DIVISION  REGION  IDU  ALCDRUG
29640     2019  1249952       5        -9     5        2         7       -9        0        6        0       1        2       -9     2       2    2        3        0       19    8     5       4      -9        1     2     1     1       1      -9      -9      1     -9     -9         3        -9        -9       -9        1                    1       1        0       0       0        0         0       0        0         0        0        0        0        0        0         0       0       0         0         7       3    0        1
1409993   2019   425369      36        -9     4        1         7       -9        5        6        1       4        2        1    -9       1    2        3       -9       19    9     4       4       5        2     2     1     1       1      -9      -9      3     -9     -9         4        -9        -9       -9       -9                    1       1        0       0       0        0         0       0        0         0        0        0        0        0        0         0       0       0         0         2       1    0        1
1519402   2019   859302      36     35620     2        2         4       -9        1        1        0       2        2        2    -9       1    2        3       -9       19   11     7       3      -9        1     2     1     1       1      -9      -9      3     -9     -9         2        -9        -9       -9       -9                    1       1        0       0       0        0         0       0        0         0        0        0        0        0        0         0       0       0         0         2       1    0        1
1324021   2019  1714982      35        -9     3        1         5       -9        1        1        0       3        1        1    -9       1    2       -9        1        4   11     5       5      -9        3     2     5    -9       1      -9      -9     -9     -9     -9         2         5        -9        2        5                    5       1        0       0       1        0         0       0        0         0        0        0        0        0        0         0       0       0         0         8       4    0        3
104377    2019  1542089       4        -9    -9        1         7       -9        2        1        2       4        2        2    -9       1    2       -9       -9        9   10     5       4       5       -9     2     4     1       1       2      -9      1      1     -9         1         1        -9        2        4                    2       1        0       1       0        0         0       0        0         0        0        0        0        0        0         0       0       0         0         8       4    0        3

- Display each column name along with its corresponding data type for the 2021 dataset.

In [265]:
df_2021.dtypes

ADMYR                  int64
CASEID                 int64
STFIPS                 int64
EDUC                   int64
MARSTAT                int64
SERVICES               int64
DETCRIM                int64
NOPRIOR                int64
PSOURCE                int64
ARRESTS                int64
EMPLOY                 int64
METHUSE                int64
PSYPROB                int64
PREG                   int64
GENDER                 int64
VET                    int64
LIVARAG                int64
DAYWAIT                int64
DSMCRIT                int64
AGE                    int64
RACE                   int64
ETHNIC                 int64
DETNLF                 int64
PRIMINC                int64
SUB1                   int64
SUB2                   int64
SUB3                   int64
ROUTE1                 int64
ROUTE2                 int64
ROUTE3                 int64
FREQ1                  int64
FREQ2                  int64
FREQ3                  int64
FRSTUSE1               int64
FRSTUSE2               int64
FRSTUSE3               int64
HLTHINS                int64
PRIMPAY                int64
FREQ_ATND_SELF_HELP    int64
ALCFLG                 int64
COKEFLG                int64
MARFLG                 int64
HERFLG                 int64
METHFLG                int64
OPSYNFLG               int64
PCPFLG                 int64
HALLFLG                int64
MTHAMFLG               int64
AMPHFLG                int64
STIMFLG                int64
BENZFLG                int64
TRNQFLG                int64
BARBFLG                int64
SEDHPFLG               int64
INHFLG                 int64
OTCFLG                 int64
OTHERFLG               int64
DIVISION               int64
REGION                 int64
IDU                    int64
ALCDRUG                int64
CBSA2020               int64
dtype: object

- Display each column name along with its corresponding data type for the 2019 dataset

In [290]:
df_2019.dtypes

ADMYR                  int64
CASEID                 int64
STFIPS                 int64
CBSA2010               int64
EDUC                   int64
MARSTAT                int64
SERVICES               int64
DETCRIM                int64
NOPRIOR                int64
PSOURCE                int64
ARRESTS                int64
EMPLOY                 int64
METHUSE                int64
PSYPROB                int64
PREG                   int64
GENDER                 int64
VET                    int64
LIVARAG                int64
DAYWAIT                int64
DSMCRIT                int64
AGE                    int64
RACE                   int64
ETHNIC                 int64
DETNLF                 int64
PRIMINC                int64
SUB1                   int64
SUB2                   int64
SUB3                   int64
ROUTE1                 int64
ROUTE2                 int64
ROUTE3                 int64
FREQ1                  int64
FREQ2                  int64
FREQ3                  int64
FRSTUSE1               int64
FRSTUSE2               int64
FRSTUSE3               int64
HLTHINS                int64
PRIMPAY                int64
FREQ_ATND_SELF_HELP    int64
ALCFLG                 int64
COKEFLG                int64
MARFLG                 int64
HERFLG                 int64
METHFLG                int64
OPSYNFLG               int64
PCPFLG                 int64
HALLFLG                int64
MTHAMFLG               int64
AMPHFLG                int64
STIMFLG                int64
BENZFLG                int64
TRNQFLG                int64
BARBFLG                int64
SEDHPFLG               int64
INHFLG                 int64
OTCFLG                 int64
OTHERFLG               int64
DIVISION               int64
REGION                 int64
IDU                    int64
ALCDRUG                int64
dtype: object

- Display unique features of the 2021 dataset
    - All columns in the dataset are of integer data type, with all 1,482,543 entries containing non-null values.

In [267]:
df_2021.info(verbose=True, show_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1482543 entries, 0 to 1482542
Data columns (total 62 columns):
 #   Column               Non-Null Count    Dtype
---  ------               --------------    -----
 0   ADMYR                1482543 non-null  int64
 1   CASEID               1482543 non-null  int64
 2   STFIPS               1482543 non-null  int64
 3   EDUC                 1482543 non-null  int64
 4   MARSTAT              1482543 non-null  int64
 5   SERVICES             1482543 non-null  int64
 6   DETCRIM              1482543 non-null  int64
 7   NOPRIOR              1482543 non-null  int64
 8   PSOURCE              1482543 non-null  int64
 9   ARRESTS              1482543 non-null  int64
 10  EMPLOY               1482543 non-null  int64
 11  METHUSE              1482543 non-null  int64
 12  PSYPROB              1482543 non-null  int64
 13  PREG                 1482543 non-null  int64
 14  GENDER               1482543 non-null  int64
 15  VET                  1482543 non-null  int64
 16  LIVARAG              1482543 non-null  int64
 17  DAYWAIT              1482543 non-null  int64
 18  DSMCRIT              1482543 non-null  int64
 19  AGE                  1482543 non-null  int64
 20  RACE                 1482543 non-null  int64
 21  ETHNIC               1482543 non-null  int64
 22  DETNLF               1482543 non-null  int64
 23  PRIMINC              1482543 non-null  int64
 24  SUB1                 1482543 non-null  int64
 25  SUB2                 1482543 non-null  int64
 26  SUB3                 1482543 non-null  int64
 27  ROUTE1               1482543 non-null  int64
 28  ROUTE2               1482543 non-null  int64
 29  ROUTE3               1482543 non-null  int64
 30  FREQ1                1482543 non-null  int64
 31  FREQ2                1482543 non-null  int64
 32  FREQ3                1482543 non-null  int64
 33  FRSTUSE1             1482543 non-null  int64
 34  FRSTUSE2             1482543 non-null  int64
 35  FRSTUSE3             1482543 non-null  int64
 36  HLTHINS              1482543 non-null  int64
 37  PRIMPAY              1482543 non-null  int64
 38  FREQ_ATND_SELF_HELP  1482543 non-null  int64
 39  ALCFLG               1482543 non-null  int64
 40  COKEFLG              1482543 non-null  int64
 41  MARFLG               1482543 non-null  int64
 42  HERFLG               1482543 non-null  int64
 43  METHFLG              1482543 non-null  int64
 44  OPSYNFLG             1482543 non-null  int64
 45  PCPFLG               1482543 non-null  int64
 46  HALLFLG              1482543 non-null  int64
 47  MTHAMFLG             1482543 non-null  int64
 48  AMPHFLG              1482543 non-null  int64
 49  STIMFLG              1482543 non-null  int64
 50  BENZFLG              1482543 non-null  int64
 51  TRNQFLG              1482543 non-null  int64
 52  BARBFLG              1482543 non-null  int64
 53  SEDHPFLG             1482543 non-null  int64
 54  INHFLG               1482543 non-null  int64
 55  OTCFLG               1482543 non-null  int64
 56  OTHERFLG             1482543 non-null  int64
 57  DIVISION             1482543 non-null  int64
 58  REGION               1482543 non-null  int64
 59  IDU                  1482543 non-null  int64
 60  ALCDRUG              1482543 non-null  int64
 61  CBSA2020             1482543 non-null  int64
dtypes: int64(62)
memory usage: 701.3 MB

- Display unique features of the 2019 dataset
    - All columns in the dataset are of integer data type, with all 1,889,755 entries containing non-null values.

In [268]:
df_2019.info(verbose=True, show_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1889755 entries, 0 to 1889754
Data columns (total 62 columns):
 #   Column               Non-Null Count    Dtype
---  ------               --------------    -----
 0   ADMYR                1889755 non-null  int64
 1   CASEID               1889755 non-null  int64
 2   STFIPS               1889755 non-null  int64
 3   CBSA2010             1889755 non-null  int64
 4   EDUC                 1889755 non-null  int64
 5   MARSTAT              1889755 non-null  int64
 6   SERVICES             1889755 non-null  int64
 7   DETCRIM              1889755 non-null  int64
 8   NOPRIOR              1889755 non-null  int64
 9   PSOURCE              1889755 non-null  int64
 10  ARRESTS              1889755 non-null  int64
 11  EMPLOY               1889755 non-null  int64
 12  METHUSE              1889755 non-null  int64
 13  PSYPROB              1889755 non-null  int64
 14  PREG                 1889755 non-null  int64
 15  GENDER               1889755 non-null  int64
 16  VET                  1889755 non-null  int64
 17  LIVARAG              1889755 non-null  int64
 18  DAYWAIT              1889755 non-null  int64
 19  DSMCRIT              1889755 non-null  int64
 20  AGE                  1889755 non-null  int64
 21  RACE                 1889755 non-null  int64
 22  ETHNIC               1889755 non-null  int64
 23  DETNLF               1889755 non-null  int64
 24  PRIMINC              1889755 non-null  int64
 25  SUB1                 1889755 non-null  int64
 26  SUB2                 1889755 non-null  int64
 27  SUB3                 1889755 non-null  int64
 28  ROUTE1               1889755 non-null  int64
 29  ROUTE2               1889755 non-null  int64
 30  ROUTE3               1889755 non-null  int64
 31  FREQ1                1889755 non-null  int64
 32  FREQ2                1889755 non-null  int64
 33  FREQ3                1889755 non-null  int64
 34  FRSTUSE1             1889755 non-null  int64
 35  FRSTUSE2             1889755 non-null  int64
 36  FRSTUSE3             1889755 non-null  int64
 37  HLTHINS              1889755 non-null  int64
 38  PRIMPAY              1889755 non-null  int64
 39  FREQ_ATND_SELF_HELP  1889755 non-null  int64
 40  ALCFLG               1889755 non-null  int64
 41  COKEFLG              1889755 non-null  int64
 42  MARFLG               1889755 non-null  int64
 43  HERFLG               1889755 non-null  int64
 44  METHFLG              1889755 non-null  int64
 45  OPSYNFLG             1889755 non-null  int64
 46  PCPFLG               1889755 non-null  int64
 47  HALLFLG              1889755 non-null  int64
 48  MTHAMFLG             1889755 non-null  int64
 49  AMPHFLG              1889755 non-null  int64
 50  STIMFLG              1889755 non-null  int64
 51  BENZFLG              1889755 non-null  int64
 52  TRNQFLG              1889755 non-null  int64
 53  BARBFLG              1889755 non-null  int64
 54  SEDHPFLG             1889755 non-null  int64
 55  INHFLG               1889755 non-null  int64
 56  OTCFLG               1889755 non-null  int64
 57  OTHERFLG             1889755 non-null  int64
 58  DIVISION             1889755 non-null  int64
 59  REGION               1889755 non-null  int64
 60  IDU                  1889755 non-null  int64
 61  ALCDRUG              1889755 non-null  int64
dtypes: int64(62)
memory usage: 893.9 MB

## Data munging
Place your **data munging** code and documentation within this section.  
- Keep each of your Code cells short and focused on a single task.  
- Include a Markdown cell above each code cell that describes what task the code within the code cell is performing.
- Make as many code cells as you need to complete the munging - a few have been created for you to start with.
- Display 5 sample rows of the modified data after each transformation so a viewer can see how the data has changed.

**Note**: If you believe that your data set does not require any munging, please explain in detail.  Create Markdown cells that explain your thinking and create Code cells that show any specific structures of the data you refer to in your explanation.

1. Filter out groups with education levels other than Grades 9 to 11 or Grade 12 (or GED)

In [269]:
df_2021_clean = df_2021[(df_2021['EDUC'] == 2) | (df_2021['EDUC'] == 3)]
df_2021_clean.head()

   ADMYR   CASEID  STFIPS  EDUC  MARSTAT  SERVICES  DETCRIM  NOPRIOR  PSOURCE  ARRESTS  EMPLOY  METHUSE  PSYPROB  PREG  GENDER  VET  LIVARAG  DAYWAIT  DSMCRIT  AGE  RACE  ETHNIC  DETNLF  PRIMINC  SUB1  SUB2  SUB3  ROUTE1  ROUTE2  ROUTE3  FREQ1  FREQ2  FREQ3  FRSTUSE1  FRSTUSE2  FRSTUSE3  HLTHINS  PRIMPAY  FREQ_ATND_SELF_HELP  ALCFLG  COKEFLG  MARFLG  HERFLG  METHFLG  OPSYNFLG  PCPFLG  HALLFLG  MTHAMFLG  AMPHFLG  STIMFLG  BENZFLG  TRNQFLG  BARBFLG  SEDHPFLG  INHFLG  OTCFLG  OTHERFLG  DIVISION  REGION  IDU  ALCDRUG  CBSA2020
1   2021  1199988       2     2        1         5        3        0        7        0       4        2        1     2       2    2        2        0        7    2     5       4       5        4     4    10    19       2       2       2      3      2      3         1         3         1        4        4                    1       0        0       1       0        0         0       0        0         1        0        0        0        0        0         0       0       0         1         9       4    0        2        -9
3   2021  1146520       2     2        2         7       -9        1        1        0       4        1        2     2       2    2        3        0        5    5     5       2       1        4     5     1     1       3      -9      -9      3     -9     -9         4        -9        -9        2        4                    1       0        0       0       1        0         0       0        0         0        0        0        0        0        0         0       0       0         0         9       4    0        2     11260
4   2021  1213798       2     2        1         7       -9        5        1        0       4        1        2     2       2    2        3        0        5    5     7       2       5        3     5     1     1       4      -9      -9      3     -9     -9         4        -9        -9        2        4                    1       0        0       0       1        0         0       0        0         0        0        0        0        0        0         0       0       0         0         9       4    1        2     11260
5   2021  1364469       2     3        1         7       -9        1        6        0       4        2        2     2       2    2        2        0        4    5     4       4       5        5     2    19     7       1       3       2      2      2      3         2         5         2        2        7                    1       1        0       0       0        0         1       0        0         0        0        0        0        0        0         0       0       0         1         9       4    0        3     11260
7   2021  1228183      34     3        1         7       -9        2        1        0       4        1        2     2       2    2        3        0        5    5     1       4       1        4     5     1     1       4      -9      -9      3     -9     -9         4        -9        -9        4        4                    2       0        0       0       1        0         0       0        0         0        0        0        0        0        0         0       0       0         0         2       1    1        2     11260

In [270]:
df_2019_clean = df_2019[(df_2019['EDUC'] == 2) | (df_2019['EDUC'] == 3)]
df_2019_clean.head()

   ADMYR   CASEID  STFIPS  CBSA2010  EDUC  MARSTAT  SERVICES  DETCRIM  NOPRIOR  PSOURCE  ARRESTS  EMPLOY  METHUSE  PSYPROB  PREG  GENDER  VET  LIVARAG  DAYWAIT  DSMCRIT  AGE  RACE  ETHNIC  DETNLF  PRIMINC  SUB1  SUB2  SUB3  ROUTE1  ROUTE2  ROUTE3  FREQ1  FREQ2  FREQ3  FRSTUSE1  FRSTUSE2  FRSTUSE3  HLTHINS  PRIMPAY  FREQ_ATND_SELF_HELP  ALCFLG  COKEFLG  MARFLG  HERFLG  METHFLG  OPSYNFLG  PCPFLG  HALLFLG  MTHAMFLG  AMPHFLG  STIMFLG  BENZFLG  TRNQFLG  BARBFLG  SEDHPFLG  INHFLG  OTCFLG  OTHERFLG  DIVISION  REGION  IDU  ALCDRUG
0   2019  1666221       2     27940     3        1         4       -9        0        3        0      -9        2        2     2       2    2        3        0        9    3     8       4      -9        4     2     4     1       1       2      -9     -9     -9     -9        -9        -9        -9        2        4                    1       1        0       1       0        0         0       0        0         0        0        0        0        0        0         0       0       0         0         9       4    0        3
1   2019  1570498       2        -9     3        1         7       -9        0        6        0       4        2        2     2       2    2        3        0        4    7     5       3       5        5     2     4     1       1       2      -9      1      1     -9         2         2        -9        4        1                    2       1        0       1       0        0         0       0        0         0        0        0        0        0        0         0       0       0         0         9       4    0        3
2   2019  1547352       2     27940     3        1         4       -9        3        2        0       4        2        1    -9       2    2        3        0        4    5     2       4       4        5     2     1     1       1      -9      -9      3     -9     -9         3        -9        -9        2        4                    1       1        0       0       0        0         0       0        0         0        0        0        0        0        0         0       0       0         0         9       4    0        1
3   2019  1510020       2        -9     3        1         7       -9        0        3        0       4        1        2     2       2    2        3        0        5    5     8       4       5        5     5     4    10       4       1       2      3      2      2         3         2         3        2        4                    1       0        0       1       1        0         0       0        0         1        0        0        0        0        0         0       0       0         0         9       4    1        2
4   2019  1585912       2        -9     3        4         7       -9        1        1        1       3        2        1     2       2    2        3        0       15    5     1       4      -9        4     2     4     1       1       5      -9      2      2     -9         3         3        -9        4        7                    1       1        0       1       0        0         0       0        0         0        0        0        0        0        0         0       0       0         0         9       4    0        3

2. Filter out groups that are not categorized as current students based on the DETNLF value

In [271]:
df_2021_clean = df_2021_clean[df_2021_clean['DETNLF'] == 2]
df_2021_clean.head()

     ADMYR   CASEID  STFIPS  EDUC  MARSTAT  SERVICES  DETCRIM  NOPRIOR  PSOURCE  ARRESTS  EMPLOY  METHUSE  PSYPROB  PREG  GENDER  VET  LIVARAG  DAYWAIT  DSMCRIT  AGE  RACE  ETHNIC  DETNLF  PRIMINC  SUB1  SUB2  SUB3  ROUTE1  ROUTE2  ROUTE3  FREQ1  FREQ2  FREQ3  FRSTUSE1  FRSTUSE2  FRSTUSE3  HLTHINS  PRIMPAY  FREQ_ATND_SELF_HELP  ALCFLG  COKEFLG  MARFLG  HERFLG  METHFLG  OPSYNFLG  PCPFLG  HALLFLG  MTHAMFLG  AMPHFLG  STIMFLG  BENZFLG  TRNQFLG  BARBFLG  SEDHPFLG  INHFLG  OTCFLG  OTHERFLG  DIVISION  REGION  IDU  ALCDRUG  CBSA2020
78    2021  1298782       2     2        1         7       -9        0        4        0       4        2        1     2       2    2        3        0        8    2     1       4       2        4    19     2     1       3       1      -9     -9      2     -9         3         2        -9        4        7                    1       1        0       0       0        0         0       0        0         0        0        0        0        0        0         0       0       0         1         9       4    0        3        -9
118   2021  1429552       2     3        4         5       -9        0        2        0       4        1        2     2       2    2        3        0        4    7     1       4       2        4     2     1     1       1      -9      -9      2     -9     -9         3        -9        -9       -9        7                    2       1        0       0       0        0         0       0        0         0        0        0        0        0        0         0       0       0         0         9       4    0        1     11260
150   2021  1332528       2     2        1         6       -9        1        1        0       4        2        1     2       2    2        3        0        8    2     1       4       2        4    10     4    19       2       2       2      3      3      3         3         3         3        2        4                   -9       0        0       1       0        0         0       0        0         1        0        0        0        0        0         0       0       0         1         9       4    0        2     11260
177   2021  1110383       2     2        1         7       -9        0        3        0       4        2        1     2       2    2        3        0        7    2    -9      -9       2        4     4     2     1       2       1      -9      3      2     -9         3         3        -9        1        2                    1       1        0       1       0        0         0       0        0         0        0        0        0        0        0         0       0       0         0         9       4    0        3     11260
230   2021  1482978       2     2        1         7        8        4        7        0       4        2        1     2       2    2        2        0        7    2     1       4       2        4     4     2     1       2       1      -9      3      3     -9         2         2        -9        2        4                    1       1        0       1       0        0         0       0        0         0        0        0        0        0        0         0       0       0         0         9       4    0        3     11260

In [272]:
df_2019_clean = df_2019_clean[df_2019_clean['DETNLF'] == 2]
df_2019_clean.head()

     ADMYR   CASEID  STFIPS  CBSA2010  EDUC  MARSTAT  SERVICES  DETCRIM  NOPRIOR  PSOURCE  ARRESTS  EMPLOY  METHUSE  PSYPROB  PREG  GENDER  VET  LIVARAG  DAYWAIT  DSMCRIT  AGE  RACE  ETHNIC  DETNLF  PRIMINC  SUB1  SUB2  SUB3  ROUTE1  ROUTE2  ROUTE3  FREQ1  FREQ2  FREQ3  FRSTUSE1  FRSTUSE2  FRSTUSE3  HLTHINS  PRIMPAY  FREQ_ATND_SELF_HELP  ALCFLG  COKEFLG  MARFLG  HERFLG  METHFLG  OPSYNFLG  PCPFLG  HALLFLG  MTHAMFLG  AMPHFLG  STIMFLG  BENZFLG  TRNQFLG  BARBFLG  SEDHPFLG  INHFLG  OTCFLG  OTHERFLG  DIVISION  REGION  IDU  ALCDRUG
85    2019  1689255       2        -9     2        1         5       -9        3        6        0       4        2        2     2       2    2        2        0        7    2     5       4       2        4     4    12    13       2       1       2      3      2      2         2         2         2        2        4                   -9       0        0       1       0        0         0       0        0         0        0        1        1        0        0         0       0       0         0         9       4    0        2
189   2019  1646988       2     21820     2        1         5       -9        1        1        0       4        2        2     2       2    2        2        0        7    2     1       4       2        4     4     2     1       2       1      -9      3      1     -9         3         3        -9        2        4                    1       1        0       1       0        0         0       0        0         0        0        0        0        0        0         0       0       0         0         9       4    0        3
342   2019  1651580       2        -9     2        1         5       -9        0        1        0       4        2        1     2       2    2        3        0        8    2     5       4       2        4    10     5     4       4       4       2      1      1      2         3         3         2        2        4                    1       0        0       1       1        0         0       0        0         1        0        0        0        0        0         0       0       0         0         9       4    1        2
396   2019  1575497       2     21820     3        1         7        3        5        7        0       4        2        2     2       2    2        3        0        8    2     1       4       2        4    10     5     4       4       4       2      1      1      1         3         2         2        2        4                    2       0        0       1       1        0         0       0        0         1        0        0        0        0        0         0       0       0         0         9       4    1        2
399   2019  1783581       2        -9     2        1         5       -9        0        6        0       4        2        2     2       2    2        3        0        4    2     1       4       2        4     2    18    13       1       1       5      2      2      1         2         2         2        2        4                    1       1        0       0       0        0         0       0        0         0        0        0        1        0        0         0       0       1         0         9       4    0        3

3. Filter out groups that are not from the State of New York, which has a FIPS code of 36

In [273]:
df_2021_clean = df_2021_clean[df_2021_clean['STFIPS'] == 36]
df_2021_clean.head()

         ADMYR  CASEID  STFIPS  EDUC  MARSTAT  SERVICES  DETCRIM  NOPRIOR  PSOURCE  ARRESTS  EMPLOY  METHUSE  PSYPROB  PREG  GENDER  VET  LIVARAG  DAYWAIT  DSMCRIT  AGE  RACE  ETHNIC  DETNLF  PRIMINC  SUB1  SUB2  SUB3  ROUTE1  ROUTE2  ROUTE3  FREQ1  FREQ2  FREQ3  FRSTUSE1  FRSTUSE2  FRSTUSE3  HLTHINS  PRIMPAY  FREQ_ATND_SELF_HELP  ALCFLG  COKEFLG  MARFLG  HERFLG  METHFLG  OPSYNFLG  PCPFLG  HALLFLG  MTHAMFLG  AMPHFLG  STIMFLG  BENZFLG  TRNQFLG  BARBFLG  SEDHPFLG  INHFLG  OTCFLG  OTHERFLG  DIVISION  REGION  IDU  ALCDRUG  CBSA2020
457410    2021  803387      36     2        1         7       -9        0       -9        1       4       -9        2    -9       1   -9        2       -9        2    2     7       1       2       -9     4     1    -9       2      -9      -9      1     -9     -9         2        -9        -9       -9       -9                    1       0        0       1       0        0         0       0        0         0        0        0        0        0        0         0       0       0         0         2       1    0        2        -9
583802    2021  731749      36     2        1         7       -9        0        1        0       4        1        1     2       2    2        2       -9       19    2     7       4       2        4     4     1     1       2      -9      -9      2     -9     -9         2        -9        -9       -9       -9                    1       0        0       1       0        0         0       0        0         0        0        0        0        0        0         0       0       0         0         2       1    0        2     30460
1085048   2021  406984      36     3        1         7       -9        5        2        0       4        2        2    -9       1    2        3       -9       19    9     5       4       2        4     2     1     1       1      -9      -9      1     -9     -9         2        -9        -9       -9       -9                    1       1        0       0       0        0         0       0        0         0        0        0        0        0        0         0       0       0         0         2       1    0        1     40380
1085178   2021  366482      36     3        4         7       -9        5        1        0       4        1        1    -9       1    2        3       -9       19   10     7       3       2        5     5     3     1       3       2      -9      3      3     -9         4         4        -9       -9       -9                    5       0        1       0       1        0         0       0        0         0        0        0        0        0        0         0       0       0         0         2       1    0        2     35620
1087824   2021  508984      36     2       -9         2       -9       -9        1       -9       4        2       -9    -9       1    2        3       -9       19    9     5       4       2        5     7    10     3       1       2       2      2      3      3         4         4         4       -9       -9                   -9       0        1       0       0        0         1       0        0         1        0        0        0        0        0         0       0       0         0         2       1    0        2     15380

In [274]:
df_2019_clean = df_2019_clean[df_2019_clean['STFIPS'] == 36]
df_2019_clean.head()

         ADMYR   CASEID  STFIPS  CBSA2010  EDUC  MARSTAT  SERVICES  DETCRIM  NOPRIOR  PSOURCE  ARRESTS  EMPLOY  METHUSE  PSYPROB  PREG  GENDER  VET  LIVARAG  DAYWAIT  DSMCRIT  AGE  RACE  ETHNIC  DETNLF  PRIMINC  SUB1  SUB2  SUB3  ROUTE1  ROUTE2  ROUTE3  FREQ1  FREQ2  FREQ3  FRSTUSE1  FRSTUSE2  FRSTUSE3  HLTHINS  PRIMPAY  FREQ_ATND_SELF_HELP  ALCFLG  COKEFLG  MARFLG  HERFLG  METHFLG  OPSYNFLG  PCPFLG  HALLFLG  MTHAMFLG  AMPHFLG  STIMFLG  BENZFLG  TRNQFLG  BARBFLG  SEDHPFLG  INHFLG  OTCFLG  OTHERFLG  DIVISION  REGION  IDU  ALCDRUG
494220    2019   983893      36        -9     2        1         6        4       -9        7        0       4        1        2     2       2    2        3       -9       -9    3     4      -9       2        5     4     1     1       2      -9      -9      2     -9     -9         3        -9        -9       -9       -9                    1       0        0       1       0        0         0       0        0         0        0        0        0        0        0         0       0       0         0         2       1    0        2
740241    2019  1416316      36     30460     3        1         7        4        0        7        0       4        1        1    -9       1    2        2       -9       10    2     7       3       2        1     4     1     1       2      -9      -9      1     -9     -9         2        -9        -9       -9       -9                    1       0        0       1       0        0         0       0        0         0        0        0        0        0        0         0       0       0         0         2       1    0        2
740638    2019   985715      36     23180     2        1         7       -9        0        7        0       4        1        1    -9       1    2        2       -9       10    2     7       4       2        5     4     1     1       2      -9      -9      1     -9     -9         3        -9        -9       -9       -9                    1       0        0       1       0        0         0       0        0         0        0        0        0        0        0         0       0       0         0         2       1    0        2
1310101   2019   431193      36     35620     2        1         6       -9        0        1        0       4       -9        1     1       2    2        2       -9        7    2     5       3       2        5     4     1     1       2      -9      -9      2     -9     -9         3        -9        -9       -9       -9                   -9       0        0       1       0        0         0       0        0         0        0        0        0        0        0         0       0       0         0         2       1    0        2
1340798   2019   816823      36        -9     3        4         7       -9        3        1        0       4        1        2    -9       1    2        3       -9       19   11     4       1       2        4     5     3     4       3       3       2      1      1      3         3         3         2       -9       -9                    5       0        1       1       1        0         0       0        0         0        0        0        0        0        0         0       0       0         0         2       1    0        2

4. Standardize the `RACE` variable across two datasets:
    - Check rows where the state does not distinguish between Asian or Pacific Islander in both datasets.

In [275]:
# Delete rows with value of the states that do not distinguish Asian or pacific islander in both date sets
# 1/ Find the state 
stfips_values_race_3 = df_2019_clean.loc[df_2019_clean['RACE'] == 3, 'STFIPS'].unique()

if stfips_values_race_3.size == 0:
    print("New York distinguishes Asians from Pacific Islanders. No further processing is needed.")
else:
    print("Further munging is required.")

New York distinguishes Asians from Pacific Islanders. No further processing is needed.

5. Standardize the RACE variable across two datasets:
    - Unify numeric and categorical values.

In [276]:
# Prepare for verification
df_2019_clean.head()

         ADMYR   CASEID  STFIPS  CBSA2010  EDUC  MARSTAT  SERVICES  DETCRIM  NOPRIOR  PSOURCE  ARRESTS  EMPLOY  METHUSE  PSYPROB  PREG  GENDER  VET  LIVARAG  DAYWAIT  DSMCRIT  AGE  RACE  ETHNIC  DETNLF  PRIMINC  SUB1  SUB2  SUB3  ROUTE1  ROUTE2  ROUTE3  FREQ1  FREQ2  FREQ3  FRSTUSE1  FRSTUSE2  FRSTUSE3  HLTHINS  PRIMPAY  FREQ_ATND_SELF_HELP  ALCFLG  COKEFLG  MARFLG  HERFLG  METHFLG  OPSYNFLG  PCPFLG  HALLFLG  MTHAMFLG  AMPHFLG  STIMFLG  BENZFLG  TRNQFLG  BARBFLG  SEDHPFLG  INHFLG  OTCFLG  OTHERFLG  DIVISION  REGION  IDU  ALCDRUG
494220    2019   983893      36        -9     2        1         6        4       -9        7        0       4        1        2     2       2    2        3       -9       -9    3     4      -9       2        5     4     1     1       2      -9      -9      2     -9     -9         3        -9        -9       -9       -9                    1       0        0       1       0        0         0       0        0         0        0        0        0        0        0         0       0       0         0         2       1    0        2
740241    2019  1416316      36     30460     3        1         7        4        0        7        0       4        1        1    -9       1    2        2       -9       10    2     7       3       2        1     4     1     1       2      -9      -9      1     -9     -9         2        -9        -9       -9       -9                    1       0        0       1       0        0         0       0        0         0        0        0        0        0        0         0       0       0         0         2       1    0        2
740638    2019   985715      36     23180     2        1         7       -9        0        7        0       4        1        1    -9       1    2        2       -9       10    2     7       4       2        5     4     1     1       2      -9      -9      1     -9     -9         3        -9        -9       -9       -9                    1       0        0       1       0        0         0       0        0         0        0        0        0        0        0         0       0       0         0         2       1    0        2
1310101   2019   431193      36     35620     2        1         6       -9        0        1        0       4       -9        1     1       2    2        2       -9        7    2     5       3       2        5     4     1     1       2      -9      -9      2     -9     -9         3        -9        -9       -9       -9                   -9       0        0       1       0        0         0       0        0         0        0        0        0        0        0         0       0       0         0         2       1    0        2
1340798   2019   816823      36        -9     3        4         7       -9        3        1        0       4        1        2    -9       1    2        3       -9       19   11     4       1       2        4     5     3     4       3       3       2      1      1      3         3         3         2       -9       -9                    5       0        1       1       1        0         0       0        0         0        0        0        0        0        0         0       0       0         0         2       1    0        2

In [277]:
# 1/ Alska Native & American Indian
df_2019_clean['RACE'].replace(2, 1, inplace=True)

In [278]:
# 2/ Asian
df_2019_clean['RACE'].replace(6, 2, inplace=True)

In [279]:
# 3/ Black or African American
df_2019_clean['RACE'].replace(4, 3, inplace=True)

In [280]:
# 4/ Native Hawaiian or Other Pacific Islander
df_2019_clean['RACE'].replace(9, 4, inplace=True)

In [281]:
# 5/ Other single race & Two or more races
df_2019_clean['RACE'].replace(7, 6, inplace=True)
df_2019_clean['RACE'].replace(8, 6, inplace=True)

In [282]:
# Verification
df_2019_clean.head()

         ADMYR   CASEID  STFIPS  CBSA2010  EDUC  MARSTAT  SERVICES  DETCRIM  NOPRIOR  PSOURCE  ARRESTS  EMPLOY  METHUSE  PSYPROB  PREG  GENDER  VET  LIVARAG  DAYWAIT  DSMCRIT  AGE  RACE  ETHNIC  DETNLF  PRIMINC  SUB1  SUB2  SUB3  ROUTE1  ROUTE2  ROUTE3  FREQ1  FREQ2  FREQ3  FRSTUSE1  FRSTUSE2  FRSTUSE3  HLTHINS  PRIMPAY  FREQ_ATND_SELF_HELP  ALCFLG  COKEFLG  MARFLG  HERFLG  METHFLG  OPSYNFLG  PCPFLG  HALLFLG  MTHAMFLG  AMPHFLG  STIMFLG  BENZFLG  TRNQFLG  BARBFLG  SEDHPFLG  INHFLG  OTCFLG  OTHERFLG  DIVISION  REGION  IDU  ALCDRUG
494220    2019   983893      36        -9     2        1         6        4       -9        7        0       4        1        2     2       2    2        3       -9       -9    3     3      -9       2        5     4     1     1       2      -9      -9      2     -9     -9         3        -9        -9       -9       -9                    1       0        0       1       0        0         0       0        0         0        0        0        0        0        0         0       0       0         0         2       1    0        2
740241    2019  1416316      36     30460     3        1         7        4        0        7        0       4        1        1    -9       1    2        2       -9       10    2     6       3       2        1     4     1     1       2      -9      -9      1     -9     -9         2        -9        -9       -9       -9                    1       0        0       1       0        0         0       0        0         0        0        0        0        0        0         0       0       0         0         2       1    0        2
740638    2019   985715      36     23180     2        1         7       -9        0        7        0       4        1        1    -9       1    2        2       -9       10    2     6       4       2        5     4     1     1       2      -9      -9      1     -9     -9         3        -9        -9       -9       -9                    1       0        0       1       0        0         0       0        0         0        0        0        0        0        0         0       0       0         0         2       1    0        2
1310101   2019   431193      36     35620     2        1         6       -9        0        1        0       4       -9        1     1       2    2        2       -9        7    2     5       3       2        5     4     1     1       2      -9      -9      2     -9     -9         3        -9        -9       -9       -9                   -9       0        0       1       0        0         0       0        0         0        0        0        0        0        0         0       0       0         0         2       1    0        2
1340798   2019   816823      36        -9     3        4         7       -9        3        1        0       4        1        2    -9       1    2        3       -9       19   11     3       1       2        4     5     3     4       3       3       2      1      1      3         3         3         2       -9       -9                    5       0        1       1       1        0         0       0        0         0        0        0        0        0        0         0       0       0         0         2       1    0        2

5. Delete rows that have been recoded between the two data sets, and are inrrelevant to the analysis

In [283]:
# Prepare for verification
df_2021_clean.head()

         ADMYR  CASEID  STFIPS  EDUC  MARSTAT  SERVICES  DETCRIM  NOPRIOR  PSOURCE  ARRESTS  EMPLOY  METHUSE  PSYPROB  PREG  GENDER  VET  LIVARAG  DAYWAIT  DSMCRIT  AGE  RACE  ETHNIC  DETNLF  PRIMINC  SUB1  SUB2  SUB3  ROUTE1  ROUTE2  ROUTE3  FREQ1  FREQ2  FREQ3  FRSTUSE1  FRSTUSE2  FRSTUSE3  HLTHINS  PRIMPAY  FREQ_ATND_SELF_HELP  ALCFLG  COKEFLG  MARFLG  HERFLG  METHFLG  OPSYNFLG  PCPFLG  HALLFLG  MTHAMFLG  AMPHFLG  STIMFLG  BENZFLG  TRNQFLG  BARBFLG  SEDHPFLG  INHFLG  OTCFLG  OTHERFLG  DIVISION  REGION  IDU  ALCDRUG  CBSA2020
457410    2021  803387      36     2        1         7       -9        0       -9        1       4       -9        2    -9       1   -9        2       -9        2    2     7       1       2       -9     4     1    -9       2      -9      -9      1     -9     -9         2        -9        -9       -9       -9                    1       0        0       1       0        0         0       0        0         0        0        0        0        0        0         0       0       0         0         2       1    0        2        -9
583802    2021  731749      36     2        1         7       -9        0        1        0       4        1        1     2       2    2        2       -9       19    2     7       4       2        4     4     1     1       2      -9      -9      2     -9     -9         2        -9        -9       -9       -9                    1       0        0       1       0        0         0       0        0         0        0        0        0        0        0         0       0       0         0         2       1    0        2     30460
1085048   2021  406984      36     3        1         7       -9        5        2        0       4        2        2    -9       1    2        3       -9       19    9     5       4       2        4     2     1     1       1      -9      -9      1     -9     -9         2        -9        -9       -9       -9                    1       1        0       0       0        0         0       0        0         0        0        0        0        0        0         0       0       0         0         2       1    0        1     40380
1085178   2021  366482      36     3        4         7       -9        5        1        0       4        1        1    -9       1    2        3       -9       19   10     7       3       2        5     5     3     1       3       2      -9      3      3     -9         4         4        -9       -9       -9                    5       0        1       0       1        0         0       0        0         0        0        0        0        0        0         0       0       0         0         2       1    0        2     35620
1087824   2021  508984      36     2       -9         2       -9       -9        1       -9       4        2       -9    -9       1    2        3       -9       19    9     5       4       2        5     7    10     3       1       2       2      2      3      3         4         4         4       -9       -9                   -9       0        1       0       0        0         1       0        0         1        0        0        0        0        0         0       0       0         0         2       1    0        2     15380

In [284]:
# Delete ETHNIC, LIVARAG, and CBSA
df_2021_clean = df_2021_clean.drop(['ETHNIC', 'LIVARAG','CBSA2020'], axis=1)

In [285]:
# Verification
df_2021_clean.head()

         ADMYR  CASEID  STFIPS  EDUC  MARSTAT  SERVICES  DETCRIM  NOPRIOR  PSOURCE  ARRESTS  EMPLOY  METHUSE  PSYPROB  PREG  GENDER  VET  DAYWAIT  DSMCRIT  AGE  RACE  DETNLF  PRIMINC  SUB1  SUB2  SUB3  ROUTE1  ROUTE2  ROUTE3  FREQ1  FREQ2  FREQ3  FRSTUSE1  FRSTUSE2  FRSTUSE3  HLTHINS  PRIMPAY  FREQ_ATND_SELF_HELP  ALCFLG  COKEFLG  MARFLG  HERFLG  METHFLG  OPSYNFLG  PCPFLG  HALLFLG  MTHAMFLG  AMPHFLG  STIMFLG  BENZFLG  TRNQFLG  BARBFLG  SEDHPFLG  INHFLG  OTCFLG  OTHERFLG  DIVISION  REGION  IDU  ALCDRUG
457410    2021  803387      36     2        1         7       -9        0       -9        1       4       -9        2    -9       1   -9       -9        2    2     7       2       -9     4     1    -9       2      -9      -9      1     -9     -9         2        -9        -9       -9       -9                    1       0        0       1       0        0         0       0        0         0        0        0        0        0        0         0       0       0         0         2       1    0        2
583802    2021  731749      36     2        1         7       -9        0        1        0       4        1        1     2       2    2       -9       19    2     7       2        4     4     1     1       2      -9      -9      2     -9     -9         2        -9        -9       -9       -9                    1       0        0       1       0        0         0       0        0         0        0        0        0        0        0         0       0       0         0         2       1    0        2
1085048   2021  406984      36     3        1         7       -9        5        2        0       4        2        2    -9       1    2       -9       19    9     5       2        4     2     1     1       1      -9      -9      1     -9     -9         2        -9        -9       -9       -9                    1       1        0       0       0        0         0       0        0         0        0        0        0        0        0         0       0       0         0         2       1    0        1
1085178   2021  366482      36     3        4         7       -9        5        1        0       4        1        1    -9       1    2       -9       19   10     7       2        5     5     3     1       3       2      -9      3      3     -9         4         4        -9       -9       -9                    5       0        1       0       1        0         0       0        0         0        0        0        0        0        0         0       0       0         0         2       1    0        2
1087824   2021  508984      36     2       -9         2       -9       -9        1       -9       4        2       -9    -9       1    2       -9       19    9     5       2        5     7    10     3       1       2       2      2      3      3         4         4         4       -9       -9                   -9       0        1       0       0        0         1       0        0         1        0        0        0        0        0         0       0       0         0         2       1    0        2

In [286]:
# Prepare for verification
df_2019_clean.head()

         ADMYR   CASEID  STFIPS  CBSA2010  EDUC  MARSTAT  SERVICES  DETCRIM  NOPRIOR  PSOURCE  ARRESTS  EMPLOY  METHUSE  PSYPROB  PREG  GENDER  VET  LIVARAG  DAYWAIT  DSMCRIT  AGE  RACE  ETHNIC  DETNLF  PRIMINC  SUB1  SUB2  SUB3  ROUTE1  ROUTE2  ROUTE3  FREQ1  FREQ2  FREQ3  FRSTUSE1  FRSTUSE2  FRSTUSE3  HLTHINS  PRIMPAY  FREQ_ATND_SELF_HELP  ALCFLG  COKEFLG  MARFLG  HERFLG  METHFLG  OPSYNFLG  PCPFLG  HALLFLG  MTHAMFLG  AMPHFLG  STIMFLG  BENZFLG  TRNQFLG  BARBFLG  SEDHPFLG  INHFLG  OTCFLG  OTHERFLG  DIVISION  REGION  IDU  ALCDRUG
494220    2019   983893      36        -9     2        1         6        4       -9        7        0       4        1        2     2       2    2        3       -9       -9    3     3      -9       2        5     4     1     1       2      -9      -9      2     -9     -9         3        -9        -9       -9       -9                    1       0        0       1       0        0         0       0        0         0        0        0        0        0        0         0       0       0         0         2       1    0        2
740241    2019  1416316      36     30460     3        1         7        4        0        7        0       4        1        1    -9       1    2        2       -9       10    2     6       3       2        1     4     1     1       2      -9      -9      1     -9     -9         2        -9        -9       -9       -9                    1       0        0       1       0        0         0       0        0         0        0        0        0        0        0         0       0       0         0         2       1    0        2
740638    2019   985715      36     23180     2        1         7       -9        0        7        0       4        1        1    -9       1    2        2       -9       10    2     6       4       2        5     4     1     1       2      -9      -9      1     -9     -9         3        -9        -9       -9       -9                    1       0        0       1       0        0         0       0        0         0        0        0        0        0        0         0       0       0         0         2       1    0        2
1310101   2019   431193      36     35620     2        1         6       -9        0        1        0       4       -9        1     1       2    2        2       -9        7    2     5       3       2        5     4     1     1       2      -9      -9      2     -9     -9         3        -9        -9       -9       -9                   -9       0        0       1       0        0         0       0        0         0        0        0        0        0        0         0       0       0         0         2       1    0        2
1340798   2019   816823      36        -9     3        4         7       -9        3        1        0       4        1        2    -9       1    2        3       -9       19   11     3       1       2        4     5     3     4       3       3       2      1      1      3         3         3         2       -9       -9                    5       0        1       1       1        0         0       0        0         0        0        0        0        0        0         0       0       0         0         2       1    0        2

In [287]:
# Delete ETHNIC, LIVARAG, and CBSA
df_2019_clean = df_2019_clean.drop(['ETHNIC', 'LIVARAG','CBSA2010'], axis=1)

In [288]:
# Verification
df_2019_clean.head()

         ADMYR   CASEID  STFIPS  EDUC  MARSTAT  SERVICES  DETCRIM  NOPRIOR  PSOURCE  ARRESTS  EMPLOY  METHUSE  PSYPROB  PREG  GENDER  VET  DAYWAIT  DSMCRIT  AGE  RACE  DETNLF  PRIMINC  SUB1  SUB2  SUB3  ROUTE1  ROUTE2  ROUTE3  FREQ1  FREQ2  FREQ3  FRSTUSE1  FRSTUSE2  FRSTUSE3  HLTHINS  PRIMPAY  FREQ_ATND_SELF_HELP  ALCFLG  COKEFLG  MARFLG  HERFLG  METHFLG  OPSYNFLG  PCPFLG  HALLFLG  MTHAMFLG  AMPHFLG  STIMFLG  BENZFLG  TRNQFLG  BARBFLG  SEDHPFLG  INHFLG  OTCFLG  OTHERFLG  DIVISION  REGION  IDU  ALCDRUG
494220    2019   983893      36     2        1         6        4       -9        7        0       4        1        2     2       2    2       -9       -9    3     3       2        5     4     1     1       2      -9      -9      2     -9     -9         3        -9        -9       -9       -9                    1       0        0       1       0        0         0       0        0         0        0        0        0        0        0         0       0       0         0         2       1    0        2
740241    2019  1416316      36     3        1         7        4        0        7        0       4        1        1    -9       1    2       -9       10    2     6       2        1     4     1     1       2      -9      -9      1     -9     -9         2        -9        -9       -9       -9                    1       0        0       1       0        0         0       0        0         0        0        0        0        0        0         0       0       0         0         2       1    0        2
740638    2019   985715      36     2        1         7       -9        0        7        0       4        1        1    -9       1    2       -9       10    2     6       2        5     4     1     1       2      -9      -9      1     -9     -9         3        -9        -9       -9       -9                    1       0        0       1       0        0         0       0        0         0        0        0        0        0        0         0       0       0         0         2       1    0        2
1310101   2019   431193      36     2        1         6       -9        0        1        0       4       -9        1     1       2    2       -9        7    2     5       2        5     4     1     1       2      -9      -9      2     -9     -9         3        -9        -9       -9       -9                   -9       0        0       1       0        0         0       0        0         0        0        0        0        0        0         0       0       0         0         2       1    0        2
1340798   2019   816823      36     3        4         7       -9        3        1        0       4        1        2    -9       1    2       -9       19   11     3       2        4     5     3     4       3       3       2      1      1      3         3         3         2       -9       -9                    5       0        1       1       1        0         0       0        0         0        0        0        0        0        0         0       0       0         0         2       1    0        2

> The two datasets now only contain data related to New York students who are in grades 9 to 11 or 12 (or GED) at the time the data is collected. All variables in the processed dataset have been unified to ensure that analysis between the two datasets can be easily performed without further manipulation.

## Data analysis
Place your **data analysis** code and documentation within this section.
- Perform at least 5 different statistical or other analyses of different aspects of the data.
    - Your analyses must be specific and relevant to your chosen data set and show interesting aspects of it.
    - Include at least one analysis that includes grouping rows by a shared attribute and performing some kind of statistical analysis on each group.
    - Sort the data in at least 1 of your analyses, but sort on its own does not constitute an analysis on its own.
- Keep each of your Code cells short and focused on a single task.
- Include a Markdown cell above each Code cell that describes what task the code within the Code cell is performing.
- Make as many code cells as you need to complete the analysis - a few have been created for you to start with.

1. Diagnoses of substance use problems in grade 12 in the 2019 dataset, sorted in descending order.
    - With a total count of 447, the most reported issue is **Other mental health condition** (234), followed by **Cannabis dependence** (65) and **Opioid dependence** (41). This underscores the importance of implementing targeted interventions and support systems to address substance use problems, especially the need to include other conditions apart from substances widely recognized as addictive, such as cannabis and opioids.

In [289]:
dsmcrit_mapping = {
    1: 'Alcohol-induced disorder',
    2: 'Substance-induced disorder',
    3: 'Alcohol intoxication',
    4: 'Alcohol dependence',
    5: 'Opioid dependence',
    6: 'Cocaine dependence',
    7: 'Cannabis dependence',
    8: 'Other substance dependence',
    9: 'Alcohol abuse',
    10: 'Cannabis abuse',
    11: 'Other substance abuse',
    12: 'Opioid abuse',
    13: 'Cocaine abuse',
    14: 'Anxiety disorders',
    15: 'Depressive disorders',
    16: 'Schizophrenia/other psychotic disorders',
    17: 'Bipolar disorders',
    18: 'Attention deficit/disruptive behavior disorders',
    19: 'Other mental health condition',
    -9: 'Missing/unknown/not collected/invalid/no or deferred diagnosis'
}

counts_dsmcrit_g12_2019 = df_2019_clean[df_2019_clean['EDUC'] == 3]['DSMCRIT'].value_counts().sort_values()
counts_dsmcrit_g12_2019.index = counts_dsmcrit_g12_2019.index.map(dsmcrit_mapping)
counts_dsmcrit_g12_2019 = counts_dsmcrit_g12_2019.sort_values(ascending=False)

print(counts_dsmcrit_g12_2019)
print("Total counts:", counts_dsmcrit_g12_2019.sum())

DSMCRIT
Other mental health condition    234
Cannabis dependence               65
Opioid dependence                 41
Alcohol dependence                41
Cannabis abuse                    22
Cocaine dependence                15
Other substance dependence        10
Alcohol abuse                     10
Opioid abuse                       5
Other substance abuse              2
Cocaine abuse                      2
Name: count, dtype: int64
Total counts: 447

## Data visualization
In this section, you will create a few **visualizations** that show some of the insights you have gathered from this data.
- Create at least 5 different visualizations, where each visualization shows different insights into the data.
- Use at least 3 different visualization types (e.g. bar charts, line charts, stacked area charts, pie charts, etc)
- Create a Markdown cell and a Code cell for each, where you explain and show the visualizations, respectively.
- Create as many additional cells as you need to prepare the data for the visualizations.